# Generated by Django 5.1 on 2024-08-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('golf_results', models.CharField(max_length=200, null=True)),
                ('cocktail_results', models.CharField(max_length=200, null=True)),
                ('past_results', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
