# Generated by Django 4.2.15 on 2024-08-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='partner_names',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
