# Generated by Django 4.2.15 on 2024-09-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0002_couple_partner_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('number_holes', models.IntegerField(choices=[])),
                ('teams_playing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.couple')),
            ],
        ),
        migrations.CreateModel(
            name='GolfCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.IntegerField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.couple')),
            ],
        ),
    ]
