# Generated by Django 4.2.15 on 2024-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0003_golfgame_golfcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfgame',
            name='number_holes',
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
