# Generated by Django 4.2.15 on 2024-09-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0004_alter_golfgame_number_holes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfgame',
            name='number_holes',
            field=models.CharField(choices=[('9', 'Nine'), ('18', 'Eighteen')], max_length=200),
        ),
    ]
