# Generated by Django 4.2.15 on 2025-01-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0005_alter_golfgame_number_holes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfgame',
            name='number_holes',
            field=models.IntegerField(),
        ),
    ]
