# Generated by Django 4.2.15 on 2025-01-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0006_alter_golfgame_number_holes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfgame',
            name='teams_playing',
            field=models.CharField(max_length=200),
        ),
    ]
