# Generated by Django 4.2.15 on 2025-01-30 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0007_alter_golfgame_teams_playing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfcard',
            name='team_id',
        ),
        migrations.AddField(
            model_name='golfcard',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.golfgame'),
        ),
        migrations.AlterField(
            model_name='golfcard',
            name='results',
            field=models.CharField(max_length=200),
        ),
    ]
