# Generated by Django 4.2.15 on 2025-01-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0008_remove_golfcard_team_id_golfcard_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfgame',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
