# Generated by Django 4.2.15 on 2025-01-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0009_golfgame_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfgame',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
