# Generated by Django 4.2.15 on 2025-02-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0010_alter_golfgame_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfgame',
            name='current_hole',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golfgame',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
