# Generated by Django 4.2.15 on 2025-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0011_golfgame_current_hole_alter_golfgame_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcard',
            name='team_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
