# Generated by Django 4.2.15 on 2025-02-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0012_golfcard_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfcard',
            name='team_id',
        ),
        migrations.AddField(
            model_name='golfcard',
            name='team_count',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
