# Generated by Django 4.2.15 on 2025-02-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0013_remove_golfcard_team_id_golfcard_team_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcard',
            name='team_count',
            field=models.IntegerField(),
        ),
    ]
