# Generated by Django 4.2.15 on 2025-02-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0014_alter_golfcard_team_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfgame',
            name='current_hole',
        ),
        migrations.AddField(
            model_name='golfcard',
            name='current_hole',
            field=models.IntegerField(default=0),
        ),
    ]
