# Generated by Django 4.2.15 on 2025-02-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0015_remove_golfgame_current_hole_golfcard_current_hole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='team',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
