# Generated by Django 4.2.15 on 2025-02-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0016_alter_couple_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
