# Generated by Django 4.2.15 on 2025-02-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0017_golfcard_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcard',
            name='score',
            field=models.CharField(max_length=200),
        ),
    ]
