# Generated by Django 4.2.15 on 2025-02-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0018_alter_golfcard_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcard',
            name='driver_count',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
