# Generated by Django 4.2.15 on 2025-02-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0019_golfcard_driver_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcard',
            name='card_driver',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
