# Generated by Django 4.2.15 on 2025-02-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0020_golfcard_card_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcard',
            name='over_drivers',
            field=models.CharField(default=[], max_length=200),
        ),
    ]
