# Generated by Django 4.2.15 on 2025-02-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0021_golfcard_over_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcard',
            name='allowed_drivers',
            field=models.CharField(default=[], max_length=200),
        ),
    ]
