# Generated by Django 4.2.15 on 2025-02-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0022_golfcard_allowed_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcard',
            name='powers',
            field=models.CharField(default={}, max_length=200),
        ),
    ]
