# Generated by Django 4.2.15 on 2025-06-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0023_golfcard_powers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compeition_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=200)),
                ('presentation_score', models.IntegerField(null=True)),
                ('presentation_comments', models.CharField(max_length=500, null=True)),
                ('taste_score', models.IntegerField(null=True)),
                ('taste_comments', models.CharField(max_length=500, null=True)),
                ('creativity_score', models.IntegerField(null=True)),
                ('creativity_comments', models.CharField(max_length=500, null=True)),
                ('theme_score', models.IntegerField(null=True)),
                ('theme_comments', models.CharField(max_length=500, null=True)),
                ('drinkability_score', models.IntegerField(null=True)),
                ('drinkability_comments', models.CharField(max_length=500, null=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teams', models.CharField(max_length=200)),
                ('cocktail_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.cocktailcard')),
                ('golf_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.golfcard')),
            ],
        ),
    ]
