# Generated by Django 4.2.15 on 2025-06-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0024_cocktailcard_user_competitionstart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailcard',
            name='compeition_id',
        ),
    ]
