# Generated by Django 4.2.15 on 2025-06-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0025_remove_cocktailcard_compeition_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktailcard',
            old_name='team_name',
            new_name='team',
        ),
    ]
