# Generated by Django 4.2.15 on 2025-06-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0026_rename_team_name_cocktailcard_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailcard',
            name='creativity_score',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='drinkability_score',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='presentation_score',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='taste_score',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='theme_score',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
