# Generated by Django 4.2.15 on 2025-06-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0027_alter_cocktailcard_creativity_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailcard',
            name='total',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
