# Generated by Django 4.2.15 on 2025-06-23 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0028_alter_cocktailcard_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktailcard',
            old_name='team',
            new_name='teams',
        ),
    ]
