# Generated by Django 4.2.15 on 2025-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0029_rename_team_cocktailcard_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailcard',
            name='creativity_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='drinkability_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='presentation_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='taste_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktailcard',
            name='theme_comments',
            field=models.TextField(null=True),
        ),
    ]
