# Generated by Django 4.2.15 on 2025-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0030_alter_cocktailcard_creativity_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailcard',
            name='order',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
