# Generated by Django 4.2.15 on 2025-06-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0031_cocktailcard_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cocktaile_name', models.CharField(max_length=255, null=True)),
                ('alcohol_base', models.CharField(max_length=255, null=True)),
                ('mixers', models.CharField(max_length=255, null=True)),
                ('garnish', models.CharField(max_length=250)),
                ('total_score', models.CharField(max_length=250, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.couple')),
            ],
        ),
    ]
