# Generated by Django 4.2.15 on 2025-06-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0032_cocktail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailcard',
            name='cocktail_list',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
