# Generated by Django 4.2.15 on 2025-06-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0033_cocktailcard_cocktail_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='cocktaile_name',
            new_name='cocktail_name',
        ),
    ]
