# Generated by Django 4.2.15 on 2025-07-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0034_rename_cocktaile_name_cocktail_cocktail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailcard',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
    ]
