# Generated by Django 4.2.15 on 2025-07-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0035_cocktailcard_current_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='partner_names',
        ),
    ]
