# Generated by Django 4.2.15 on 2025-07-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0036_remove_couple_partner_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='partner_names',
            field=models.ManyToManyField(related_name='teams', to='cocktail_comp.user'),
        ),
    ]
