# Generated by Django 4.2.15 on 2025-07-11 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktail_comp', '0037_couple_partner_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='partner_names',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
