# Generated by Django 4.2.15 on 2025-07-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0038_alter_couple_partner_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
