# Generated by Django 4.2.15 on 2025-07-23 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktail_comp', '0040_cocktailcard_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailcard',
            name='cocktail_list',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='creativity_comments',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='creativity_score',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='drinkability_comments',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='drinkability_score',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='presentation_comments',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='presentation_score',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='taste_comments',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='taste_score',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='theme_comments',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='theme_score',
        ),
        migrations.RemoveField(
            model_name='cocktailcard',
            name='total',
        ),
        migrations.CreateModel(
            name='CocktailScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_score', models.CharField(max_length=500, null=True)),
                ('presentation_comments', models.TextField(null=True)),
                ('taste_score', models.CharField(max_length=500, null=True)),
                ('taste_comments', models.TextField(null=True)),
                ('creativity_score', models.CharField(max_length=500, null=True)),
                ('creativity_comments', models.TextField(null=True)),
                ('theme_score', models.CharField(max_length=500, null=True)),
                ('theme_comments', models.TextField(null=True)),
                ('drinkability_score', models.CharField(max_length=500, null=True)),
                ('drinkability_comments', models.TextField(null=True)),
                ('total', models.CharField(max_length=500, null=True)),
                ('comp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.cocktailcard')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
