# Generated by Django 4.2.15 on 2025-07-24 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0041_remove_cocktailcard_cocktail_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailscores',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktail_comp.competitionstart'),
        ),
    ]
