# Generated by Django 4.2.15 on 2025-07-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_comp', '0042_alter_cocktailscores_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailscores',
            name='index',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
